{% set name = "fish" %}
{% set version = "4.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fish-shell/fish-shell/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.xz
  sha256: 2fda5bd970357064d8d4c896e08285ba59965ca2a8c4829ca8a82bf3b89c69f3

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
    - gettext
  host:
    - gettext
    - ncurses
    - pcre2
    - zlib
  run:

test:
  commands:
    - fish -v
    - fish_indent -v
    # - fish_key_reader -v  # returns 1 for any flag, so we can't really test it.

about:
  home: https://fishshell.com/
  license: GPL-2.0-only AND BSD-3-Clause
  license_file:
    - COPYING
  summary: The user-friendly command line shell.
  doc_url: https://fishshell.com/docs/current/index.html
  dev_url: https://github.com/fish-shell/fish-shell

extra:
  recipe-maintainers:
    - chrisburr
    - mdraw
