{% set name = "fish" %}
{% set version = "3.1.2" %}
{% set sha256 = "d5b927203b5ca95da16f514969e2a91a537b2f75bec9b21a584c4cd1c7aa74ed" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fish-shell/fish-shell/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pcre2
  host:
    - ncurses
  run:
    - ncurses
    - pcre2

test:
  commands:
    - fish -v
    - fish_indent -v
    # - fish_key_reader -v  # returns 1 for any flag, so we can't really test it.

about:
  home: https://fishshell.com/
  license: GPL-2.0-only
  license_file: COPYING
  summary: The user-friendly command line shell.
  doc_url: https://fishshell.com/docs/current/index.html
  dev_url: https://github.com/fish-shell/fish-shell

extra:
  recipe-maintainers:
    - mdraw
