{% set name = "fish" %}
{% set version = "3.1.1" %}
{% set sha256 = "07dc78eea3bc4cbd490b2f2a2e19e5771ac9e3b6b1a75893039ad8b34d6122b8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fish-shell/fish-shell/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pcre2
  host:
    - ncurses
  run:
    - ncurses
    - pcre2

test:
  commands:
    - fish -v
    - fish_indent -v
    # - fish_key_reader -v  # returns 1 for any flag, so we can't really test it.

about:
  home: https://fishshell.com/
  license: GPL-2.0-only
  license_file: COPYING
  summary: The user-friendly command line shell.
  doc_url: https://fishshell.com/docs/current/index.html
  dev_url: https://github.com/fish-shell/fish-shell

extra:
  recipe-maintainers:
    - mdraw
