{% set name = "fish" %}
{% set version = "3.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fish-shell/fish-shell/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.xz
  sha256: 291e4ec7c6c3fea54dc1aed057ce3d42b356fa6f70865627b2c7dfcecaefd210

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - gettext
  host:
    - gettext
    - ncurses
    - pcre2
    - zlib
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - fish -v
    - fish_indent -v
    # - fish_key_reader -v  # returns 1 for any flag, so we can't really test it.

about:
  home: https://fishshell.com/
  license: GPL-2.0-only AND BSD-3-Clause
  license_file:
    - COPYING
  summary: The user-friendly command line shell.
  doc_url: https://fishshell.com/docs/current/index.html
  dev_url: https://github.com/fish-shell/fish-shell

extra:
  recipe-maintainers:
    - chrisburr
    - mdraw
